image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar C:\Users\Pepper\IdeaProjects\Selenide\artifacts\app-card-delivery.jar &

build_script:
  - ./gradlew test --info "-Dselenide.headless=true"
